version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: arbitrage-postgres
    environment:
      POSTGRES_DB: arbitrage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - arbitrage-network

  redis:
    image: redis:7-alpine
    container_name: arbitrage-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - arbitrage-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arbitrage-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/arbitrage_db
      RPC_URL: ${RPC_URL}
      LOG_LEVEL: info
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - arbitrage-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  arbitrage-network:
    driver: bridge
